/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/codegen.py` from the dashboard's OpenAPI 3 spec
 * (`coord.dashboard.server.openapi_spec()`, itself built by
 * `coord/openapi.py` from `coord/models.py` / `coord/pipeline.py`) — #1550
 * (originally #750). Regenerate after any field change:
 *
 *     .venv/bin/python scripts/codegen.py
 *
 * `tests/test_generated_types_fixture.py` fails CI if this file drifts from
 * what the generator produces right now, so a stale checkout can't merge.
 */

export type AssignmentStatus =
  | 'pending'
  | 'running'
  | 'done'
  | 'failed'
  | 'cancelled'
  | 'advisory'
  | 'merged'

/**
 * coord/models.py Assignment.type's real value set — #1550 found this had
 * drifted: the hand-authored enum this replaces listed 'merge' and 'fix',
 * neither of which is ever a literal `type=` value (coord/config.py's #1137
 * audit note: a dedicated `type="merge"` was tried and reverted; `type="fix"`
 * was deliberately never introduced — both share `type="work"` with their
 * headless counterpart and are distinguished by `provider_name`/
 * `review_of_assignment_id` instead, see `attention_threshold_for`) — while
 * missing seven values that are real: 'audit' (coord/models.py docstring,
 * #885 --audit-of), and the six interactive session types from
 * coord/config.py's `INTERACTIVE_SESSION_TYPES` plus the two headless
 * lightweight-worker types from `_DEFAULT_ATTENTION_THRESHOLDS`.
 */
export type AssignmentType =
  | 'work'
  | 'review'
  | 'plan'
  | 'smoke'
  | 'conflict-fix'
  | 'mock-author'
  | 'test-author'
  | 'audit'
  | 'chat'
  | 'troubleshoot'
  | 'milestone-chat'
  | 'refinement'
  | 'new-issue-chat'
  | 'test-chat'

export type TestVerdict = 'passed' | 'failed' | 'skipped' | 'running'

/**
 * Actions supported by POST /api/pipeline/action.
 *
 * dispatch_review    — kick off an adversarial review assignment
 * dispatch_smoke     — kick off a smoke-test assignment
 * enqueue            — add to merge queue
 * merge              — merge a queued PR (must be in "pending" state)
 * post_findings      — post orphaned review findings to GitHub
 * unstick            — cancel a stuck assignment and mark it failed
 * retry              — (forthcoming) retry a failed work assignment
 * dispatch_fix       — (forthcoming) dispatch a fix for a test failure / review request-changes
 * test-verdict       — (forthcoming) record passed/failed/skipped test verdict
 * record-review-verdict — (forthcoming) record an approved/changes-requested review verdict
 */
export type PipelineAction =
  | 'dispatch_review'
  | 'dispatch_smoke'
  | 'enqueue'
  | 'merge'
  | 'post_findings'
  | 'unstick'
  | 'retry'
  | 'dispatch_fix'
  | 'test-verdict'
  | 'record-review-verdict'

export interface PipelineStage {
  name: string
  status: 'active' | 'completed' | 'skipped' | 'waiting'
  is_current: boolean
}

export interface PipelineGate {
  action: PipelineAction
  label: string
  endpoint: string
}

export interface PipelineView {
  assignment_id: string
  issue_number: number
  issue_title: string
  repo_name: string
  machine_name: string
  stages: PipelineStage[]
  current_stage: string
  available_gates: PipelineGate[]
  progress_pct: number
  review_findings_pending: boolean
  review_verdict: 'approve' | 'request-changes' | null
  review_verdict_original: string | null
  review_verdict_override_reason: string | null
  review_findings_body: string | null
  test_verdict: TestVerdict | null
  needs_attention: boolean
  needs_attention_reason: string | null
  needs_attention_detail: string | null
  finished_at: number | null
}

export interface Assignment {
  machine_name: string
  repo_name: string
  issue_number: number
  issue_title: string
  files_allowed: string[]
  files_forbidden: string[]
  briefing: string
  assignment_id: string | null
  status: AssignmentStatus
  branch: string | null
  pr_url: string | null
  dispatched_at: number | null
  finished_at: number | null
  smoke_test: 'pass' | 'fail' | null
  smoke_test_reason: string | null
  type: AssignmentType
  review_target: string | null
  review_of_assignment_id: string | null
  unreachable_count: number
  model: string | null
  plan: Record<string, unknown> | null
  review_state: 'pending' | 'dispatched' | 'done' | null
  review_dispatch_reason: string | null
  required_gates: string[]
  review_iteration: number
  review_posted_at: number | null
  test_state: TestVerdict | null
  test_reason: string | null
  test_head_sha: string | null
  test_patch_id: string | null
  test_base_sha: string | null
  test_toolchain: string | null
  review_verdict: 'approve' | 'request-changes' | null
  review_verdict_original: string | null
  review_verdict_override_reason: string | null
  review_head_sha: string | null
  review_patch_id: string | null
  review_scoped: boolean
  review_scope_base_sha: string | null
  cost_usd: number | null
  smoke_tests: string[] | null
  provider_name: string | null
  input_tokens: number
  output_tokens: number
  cache_creation_tokens: number
  cache_read_tokens: number
  failure_reason: string | null
  acceptance_state: string | null
  acceptance_reason: string | null
  acceptance_sha: string | null
  acceptance_total: number | null
  acceptance_passed: number | null
  completion_summary: string | null
  audit_goals_json: string | null
  audit_bottom_line: string | null
  audit_run_number: number | null
  for_issue_number: number | null
  driven_by: string | null
}
