/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/codegen.py` from the dashboard's OpenAPI 3 spec
 * (`coord.dashboard.server.openapi_spec()`, itself built by
 * `coord/openapi.py` from `coord/models.py` / `coord/pipeline.py`) — #1550
 * (originally #750). Regenerate after any field change:
 *
 *     .venv/bin/python scripts/codegen.py
 *
 * `tests/test_generated_types_fixture.py` fails CI if this file drifts from
 * what the generator produces right now, so a stale checkout can't merge.
 */

export type AssignmentStatus =
  | 'pending'
  | 'running'
  | 'done'
  | 'failed'
  | 'cancelled'
  | 'advisory'
  | 'merged'

/**
 * coord/models.py Assignment.type's real value set — #1550 found this had
 * drifted: the hand-authored enum this replaces listed 'merge' and 'fix',
 * neither of which is ever a literal `type=` value (coord/config.py's #1137
 * audit note: a dedicated `type="merge"` was tried and reverted; `type="fix"`
 * was deliberately never introduced — both share `type="work"` with their
 * headless counterpart and are distinguished by `provider_name`/
 * `review_of_assignment_id` instead, see `attention_threshold_for`) — while
 * missing seven values that are real: 'audit' (coord/models.py docstring,
 * #885 --audit-of), and the six interactive session types from
 * coord/config.py's `INTERACTIVE_SESSION_TYPES` plus the two headless
 * lightweight-worker types from `_DEFAULT_ATTENTION_THRESHOLDS`.
 */
export type AssignmentType =
  | 'work'
  | 'review'
  | 'plan'
  | 'smoke'
  | 'conflict-fix'
  | 'mock-author'
  | 'test-author'
  | 'audit'
  | 'chat'
  | 'troubleshoot'
  | 'milestone-chat'
  | 'refinement'
  | 'new-issue-chat'
  | 'test-chat'

export type TestVerdict = 'passed' | 'failed' | 'skipped' | 'running'

/**
 * Actions supported by POST /api/pipeline/action.
 *
 * dispatch_review    — kick off an adversarial review assignment
 * dispatch_smoke     — kick off a smoke-test assignment
 * enqueue            — add to merge queue
 * merge              — merge a queued PR (must be in "pending" state)
 * post_findings      — post orphaned review findings to GitHub
 * unstick            — cancel a stuck assignment and mark it failed
 * retry              — (forthcoming) retry a failed work assignment
 * dispatch_fix       — (forthcoming) dispatch a fix for a test failure / review request-changes
 * test-verdict       — (forthcoming) record passed/failed/skipped test verdict
 * record-review-verdict — (forthcoming) record an approved/changes-requested review verdict
 */
export type PipelineAction =
  | 'dispatch_review'
  | 'dispatch_smoke'
  | 'enqueue'
  | 'merge'
  | 'post_findings'
  | 'unstick'
  | 'retry'
  | 'dispatch_fix'
  | 'test-verdict'
  | 'record-review-verdict'

export interface PipelineStage {
  name: string
  status: 'active' | 'completed' | 'skipped' | 'waiting'
  is_current: boolean
}

export interface PipelineGate {
  action: PipelineAction
  label: string
  endpoint: string
}

export interface PipelineView {
  assignment_id: string
  issue_number: number
  issue_title: string
  repo_name: string
  machine_name: string
  stages: PipelineStage[]
  current_stage: string
  available_gates: PipelineGate[]
  progress_pct: number
  review_findings_pending: boolean
  review_verdict: 'approve' | 'request-changes' | null
  review_verdict_original: string | null
  review_verdict_override_reason: string | null
  review_findings_body: string | null
  test_verdict: TestVerdict | null
  needs_attention: boolean
  needs_attention_reason: string | null
  needs_attention_detail: string | null
  finished_at: number | null
}

export interface Assignment {
  machine_name: string
  repo_name: string
  issue_number: number
  issue_title: string
  files_allowed: string[]
  files_forbidden: string[]
  briefing: string
  assignment_id: string | null
  status: AssignmentStatus
  branch: string | null
  pr_url: string | null
  dispatched_at: number | null
  finished_at: number | null
  smoke_test: 'pass' | 'fail' | null
  smoke_test_reason: string | null
  type: AssignmentType
  review_target: string | null
  review_of_assignment_id: string | null
  unreachable_count: number
  model: string | null
  plan: Record<string, unknown> | null
  review_state: 'pending' | 'dispatched' | 'done' | null
  review_dispatch_reason: string | null
  required_gates: string[]
  review_iteration: number
  review_posted_at: number | null
  test_state: TestVerdict | null
  test_reason: string | null
  test_head_sha: string | null
  test_patch_id: string | null
  test_base_sha: string | null
  test_toolchain: string | null
  review_verdict: 'approve' | 'request-changes' | null
  review_verdict_original: string | null
  review_verdict_override_reason: string | null
  verdict_source: string | null
  verdict_source_reason: string | null
  review_head_sha: string | null
  review_patch_id: string | null
  review_scoped: boolean
  review_scope_base_sha: string | null
  cost_usd: number | null
  smoke_tests: string[] | null
  provider_name: string | null
  input_tokens: number
  output_tokens: number
  cache_creation_tokens: number
  cache_read_tokens: number
  failure_reason: string | null
  acceptance_state: string | null
  acceptance_reason: string | null
  acceptance_sha: string | null
  acceptance_total: number | null
  acceptance_passed: number | null
  completion_summary: string | null
  audit_goals_json: string | null
  audit_bottom_line: string | null
  audit_run_number: number | null
  for_issue_number: number | null
  driven_by: string | null
  stop_reason: string | null
}

// ── #2428 DQW-1 (claude-coordinator) / issue #5 (coord-web) ─────────────────
//
// Hand-added ahead of the next real `scripts/codegen.py` regeneration — that
// script and the OpenAPI spec it reads both live in claude-coordinator, not
// here (see this repo's CLAUDE.md "Generated API types drift silently"
// note), so nothing in this checkout can actually run it. Field-for-field
// transcription of what `coord.dashboard.server.openapi_spec()` serves today
// for `GET /api/drive-queue`: `BoardDriveQueueEntry` from
// `sqlite_table_schema(..., "drive_queue", ...)` (the wire shape IS the
// `drive_queue` SQLite DDL, coord/db.py — same "no hand-maintained field
// list to drift" reasoning coord/serve_app.py's `/board` schema uses) and
// `DriveQueueSummary` from `dataclass_schema(DriveQueueSummary, ...)`
// (coord/drive_queue.py). Re-diff against the real generated.ts output next
// time it's regenerated and replace this block wholesale if it drifted.
export interface BoardDriveQueueEntry {
  id: number
  repo_name: string
  issue_number: number
  position: number
  machine: string | null
  /** JSON-decoded on the wire (coord/dao.py `_JSON_COLUMNS`) — pre-req keys, e.g. ["repo#123"]. */
  after_json: string[]
  state: string
  attempts: number
  deferrals: number
  last_reason: string
  reason_at: number | null
  session_name: string | null
  launched_at: number | null
  enqueued_at: number
  hold_after: number
  hold_reason: string
  resume_when: string
  hold_state: string
  hold_probes: number
  launch_host: string
  hold_scope: string
  resumes: number
  retry_backoff_at: number | null
}

/**
 * Server-computed aggregate over a drive-queue read — see
 * `coord.drive_queue.summarize_drive_queue`/`DriveQueueSummary`. `level` is
 * the ascending-severity rank 'empty' < 'normal' < 'stalled' < 'held' <
 * 'blocked'; `scripts/codegen.py` has no `ENUM_OVERRIDES` entry for it, so
 * it's a bare `string` here, same as it would be if regenerated today.
 */
export interface DriveQueueSummary {
  level: string
  pending: number
  running: number
  waiting: number
  blocked: number
  eligible: number
  held: number
  fleet_held: number
}

// ── #2492 RPT-1 (claude-coordinator) / #21 RPT-2 (coord-web) ────────────────
//
// Hand-added ahead of the next real `scripts/codegen.py` regeneration — that
// script and the OpenAPI spec it reads both live in claude-coordinator, not
// here (see this repo's CLAUDE.md "Generated API types drift silently"
// note), so nothing in this checkout can actually run it. Same posture as
// `BoardDriveQueueEntry` above: field-for-field transcription of what
// `coord.dashboard.server.openapi_spec()` serves today for `GET /api/report`
// and `GET /api/report/{report_id}` (`coord/dashboard/server.py`'s
// `_openapi_spec`, mirroring `coord/reports.py`'s dataclasses' own
// `to_dict()`). Re-diff against the real generated.ts output next time it's
// regenerated and replace this block wholesale if it drifted.

/** One parameter of a report — rich enough that a client builds its input
 * form from the catalogue alone, never a hardcoded per-report field list. */
export interface ReportParam {
  id: string
  label: string
  /** Open vocabulary — "choice" (render a `<select>` over `choices`) or
   * "text" (a free-text `<input>`) today. */
  kind: string
  choices: string[]
  default: string
  help: string
  /** `choices` are presets, not a whitelist, when true. */
  free_form: boolean
}

/** #2454 — which two `ReportResult.columns` name the `(repo, issue)` a row
 * is about. `null` on a `ReportDef` means its rows have no single owning
 * issue (an aggregate report). */
export interface RowIdentity {
  repo_column: string
  issue_column: string
}

/** A catalogue entry — everything a client needs to render a report's tab,
 * description and parameter form, minus the server-side `run` callable. */
export interface ReportDef {
  id: string
  title: string
  description: string
  params: ReportParam[]
  row_identity: RowIdentity | null
}

export interface ReportCatalogue {
  reports: ReportDef[]
}

/** #1760 — display metadata for one `ReportResult.columns` entry, zipped by
 * array position (`id` also matches the corresponding `columns[]` entry). */
export interface ColumnMeta {
  id: string
  label: string
  /** Open vocabulary — a client meeting a `kind` it predates falls back to
   * plain stringification: "text" | "int" | "timestamp" | "list" | "enum" |
   * "duration" | "money" today. */
  kind: string
  align: string
  weight: number
}

/** #2271 — one series of a `ChartSpec`, reading its y-values off an existing
 * `ReportResult.columns` id (carries no numbers of its own). */
export interface ChartSeries {
  label: string
  column: string
  color: string | null
}

/** #2271 — an optional declaration that a `ReportResult` also reads as a
 * chart. A client that doesn't understand this block (or meets a `kind` it
 * predates) renders the table and ignores it. */
export interface ChartSpec {
  kind: string
  series: ChartSeries[]
  x: string | null
  group_by: string | null
  stacked: boolean
  title: string
  y_label: string
}

/** `GET /api/report/{report_id}`'s response shape. */
export interface ReportResult {
  report_id: string
  generated_at: number
  window: [number, number]
  columns: string[]
  column_meta: ColumnMeta[]
  rows: Array<Record<string, unknown>>
  notes: string[]
  /** #1763 — optional grand-total row keyed by the same column ids as
   * `rows`; `null` for reports with no meaningful sum. */
  totals: Record<string, unknown> | null
  chart: ChartSpec | null
}

// ── Machines panel (coord-web#61, #62, #63, #66) — blocked on claude-coordinator#3027 ──
//
// Unlike `BoardDriveQueueEntry`/`ReportDef` above, these types are NOT a
// transcription of a real, already-serving `coord.dashboard.server.
// openapi_spec()` response — the Machines API itself (routes + OpenAPI
// schema) is claude-coordinator#3027, still open at the time this landed.
// Hand-authored ahead of that landing, same "(forthcoming)" convention
// `PipelineAction`/`DriveQueueAction` (`./client.ts`) use for an action
// defined ahead of its backend route: calling any of the `fetchMachine*`
// functions in `../client.ts` against a coord server running today 404s,
// every one of them, not just the ones documented "(forthcoming)" elsewhere
// in this file. Replace this block wholesale — field names very much
// included, none of them are load-bearing yet — the day #3027 lands and
// `scripts/codegen.py` can regenerate a real one from the actual spec; do
// not assume today's field names survive that landing.

/** `GET /api/machines`/`GET /api/machines/{name}` — one machine coord's
 * roster knows about. Field selection mirrors what `SessionInfo`
 * (`./client.ts`, itself hand-written) already exposes per-session
 * (`machine`/`host`) plus the roster-level facts a Machines panel needs that
 * no existing endpoint carries.
 *
 * `severity`/`agent_version`/`is_local`/the three pause flags were added for
 * #62 (machines-list parity with coord-tui's `machines_list`, `app/mod.rs`)
 * — same "hand-authored, wholesale replaceable" posture as the rest of this
 * block, not a transcription of a real #3027 response. */
export interface MachineState {
  name: string
  /** The machine's Tailscale host, same meaning as `SessionInfo.host`. */
  host: string | null
  reachable: boolean
  /** Epoch seconds of the roster's last successful reachability probe. */
  last_seen: number | null
  active_assignments: number
  headless_workers: number
  /**
   * Rolled-up health severity across this machine's checks, computed
   * server-side the same way `_effective_severity` computes it for
   * coord-tui's `machines_list`. `'unknown'` is a first-class outcome, not a
   * styling variant of `'ok'` — the daemon currently has no verdict for this
   * machine (unreachable, never checked in, etc), and a client must never
   * render that as healthy (#62's honesty rule).
   */
  severity: 'ok' | 'warn' | 'crit' | 'unknown'
  /**
   * The coord-agent version this machine last reported, or `null` when the
   * daemon has never heard a version from it. `null` is distinct from
   * "matches local" — never rendered as drift-free just because there's
   * nothing to compare.
   */
  agent_version: string | null
  /**
   * True for the machine hosting this coord daemon itself — the version-
   * drift reference point (#62): every other machine's `agent_version`
   * compares against *this* machine's, not some separately-tracked "latest
   * release" value.
   */
  is_local: boolean
  /**
   * True while this machine is paused by the coordinator's configured
   * quiet-hours window. Distinct from `hand_paused` and `release_cordoned`
   * — coord-tui's `machines_list` renders these as three separate badges,
   * never collapsed into one "paused" pill, and its own tests pin that
   * distinction (#62).
   */
  quiet_hours_paused: boolean
  /** True while a human has explicitly paused this machine (`coord pause`),
   * independent of quiet hours or a release cordon. */
  hand_paused: boolean
  /** True while this machine is cordoned off from new work by an in-flight
   * release rollout, independent of quiet hours or a hand pause. */
  release_cordoned: boolean
  /**
   * Total on-disk size, in bytes, of this machine's git worktrees, or
   * `null` when the daemon hasn't reported one. Added for #63 (machine
   * detail's disk-footprint line) — same hand-authored, wholesale-
   * replaceable posture as the rest of this block.
   */
  worktree_bytes: number | null
  /**
   * Max concurrent headless workers this machine will run at once (its
   * concurrency ceiling), or `null` when the daemon hasn't reported one.
   * Paired with `headless_workers` (the current count) so the detail panel
   * can render "2 / 6" rather than the count alone (#63).
   */
  concurrency_limit: number | null
}

/**
 * `GET /api/machines/{name}/workers` — one of this machine's currently
 * active headless workers. `type` reuses `AssignmentType`'s real value set
 * since a worker *is* a dispatched assignment. Parity reference: coord-tui's
 * `machine_detail_list` ACTIVE WORKERS section (`app/mod.rs`). Same
 * hand-authored, wholesale-replaceable posture as the rest of this block
 * (#63) — see this section's header.
 */
export interface MachineActiveWorker {
  id: string
  issue: number | null
  type: AssignmentType
  repo: string | null
  /** Epoch seconds the worker was dispatched -- the detail panel's age
   * column is computed client-side from this. */
  started_at: number
}

/**
 * `GET /api/machines/{name}/jobs` — one entry in this machine's recent job
 * history. `status` reuses `AssignmentStatus`'s real value set since a job
 * history row *is* a (usually finished) assignment; the detail panel uses
 * it to render failures visually distinct from the rest. Parity reference:
 * coord-tui's `machine_detail_list` JOB HISTORY section (`app/mod.rs`).
 * Same hand-authored, wholesale-replaceable posture as the rest of this
 * block (#63).
 */
export interface MachineJobHistoryEntry {
  id: string
  issue: number | null
  repo: string | null
  status: AssignmentStatus
  /** Epoch seconds the job finished, or `null` while it's still
   * pending/running -- the detail panel renders those as "in progress"
   * rather than a bogus age. */
  finished_at: number | null
}

/** One sample of a `MachineMetricsSeries`.
 *
 * `value: null` is a first-class, explicit "unknown" sample (#65) — a poll
 * that failed or timed out, never a real reading. A client MUST render this
 * as a gap in the series (never interpolate across it, never plot it as
 * `0`) — plotting a failed poll as `0` would draw a dead agent as an
 * idle-but-healthy one, exactly the dishonest reading this milestone's
 * severity-verbatim / stale-labelled conventions (#62, #64) exist to rule
 * out elsewhere in the Machines panel. */
export interface MachineMetricPoint {
  /** Epoch seconds. */
  t: number
  value: number | null
}

/** `GET /api/machines/{name}/metrics` — one named time series (e.g. load,
 * disk free) for a machine, over the daemon's retained window (~6h,
 * claude-coordinator#3020). A client meeting a `metric` it doesn't
 * recognize renders it generically rather than dropping it — open
 * vocabulary, same posture `ColumnMeta.kind` documents. `src/lib/
 * machineCharts.ts`'s own doc comment lists the metric names this client
 * currently knows how to chart (`cpu_pct`, `mem_pct`, `worktree_bytes`,
 * `active_workers`, `jobs_completed`, `jobs_failed`) — hand-authored ahead
 * of #3027 landing, same wholesale-replaceable posture as the rest of this
 * block. */
export interface MachineMetricsSeries {
  metric: string
  unit: string | null
  points: MachineMetricPoint[]
}

/**
 * `GET /api/machines/{name}/health` — this machine's health-check snapshot.
 * Mirrors the wire shape coord-tui's `fleet_health.rs` already consumes for
 * the identical data (`FleetMachineHealth`, itself
 * `coord.health.fleet_snapshot`'s per-machine row in `/board`'s
 * `fleet_health.machine_health[]`) rather than inventing a new one — one
 * wire contract for "one machine's rolled-up health", read by both clients.
 *
 * `severity`/`stale` answer "trust this right now?"; `results`/`checked_at`
 * answer "what did we last see?" — kept as two separate pairs on purpose
 * (#1630, #64). A stale snapshot must render as "last measured OK, a while
 * ago", never silently as "OK": `severity` is already stale-aware
 * server-side (it becomes `'unknown'` once a machine hasn't reported in too
 * long), but `stale`+`checked_at` are what let the UI say *why* rather than
 * just rendering the downgraded verdict with no explanation.
 */
export interface MachineHealthSnapshot {
  /** Rolled-up across `results`, computed server-side the same way
   * `MachineState.severity` is — not re-derived on this side. */
  severity: 'ok' | 'warn' | 'crit' | 'unknown'
  /** True when this snapshot is too old to currently trust, per the
   * server's own staleness rule (not a client-side age comparison). */
  stale: boolean
  /** Epoch seconds of the last actual measurement, or `null` when this
   * machine has never reported health at all (old agent, or never polled). */
  checked_at: number | null
  results: MachineHealthCheckResult[]
}

/**
 * One already-rendered health-check row — the wire shape of
 * `coord.health.models.CheckResult.to_dict()` (`coord/health/checks/`:
 * disk, worktrees, toolchain, index_lock, spawned_coord, cargo_targets and
 * the rest). `severity`/`headroom` are pre-decided by the probe that
 * produced this row; nothing on this side may re-derive either from raw
 * numbers — the same rule `coord-tui/src/app/fleet_health.rs`'s module doc
 * comment spells out for the identical data. `headroom` is the load-bearing
 * field: a short, already-formatted phrase such as `"86% used (22G free)"`,
 * not a number this client formats itself. Open vocabulary on `key`.
 */
export interface MachineHealthCheckResult {
  /** Stable identity for this row (`CheckResult.key`): `check_id`, or
   * `"<check_id>:<subject>"` when the check has a subject. */
  key: string
  /** Display label, e.g. `"disk"` or `"worktrees vimcode"`. */
  label: string
  severity: 'ok' | 'warn' | 'crit' | 'unknown'
  headroom: string
  detail: string
}

/** `GET /api/machines/{name}/work-stats` — aggregate assignment throughput
 * for one machine over a server-chosen trailing window. */
export interface MachineWorkStats {
  machine: string
  window_seconds: number
  assignments_completed: number
  assignments_failed: number
  cost_usd: number | null
}

/**
 * `GET /api/fleet/health` — fleet-*scope* health checks (#66): facts about
 * the fleet as a whole (board latency, phantom-running rows, deploy-lane
 * skew, …), not any one machine's. Wire shape mirrors `coord.health.
 * fleet_snapshot.FleetHealthSnapshot.fleet_checks` / coord-tui's identically-
 * named `FleetHealthBlock.fleet_checks` (`fleet_health.rs`) — reuses
 * `MachineHealthCheckResult` row-for-row rather than inventing a second
 * "check result" shape, since a fleet-scope check and a machine-scope check
 * are rendered the same way (severity + headroom + detail), just scoped
 * differently. Same hand-authored, wholesale-replaceable posture as the rest
 * of this block: this route isn't registered on any coord server yet either.
 *
 * `FleetSummary` (`src/components/FleetSummary.tsx`) is what mirrors
 * `coord.health.aggregate`'s counting rule client-side: one unit per
 * machine's already-rolled-up `MachineState.severity`, plus one unit per
 * entry here — see that component's doc comment, and `coord-tui/src/app/
 * fleet_health.rs`'s module doc comment for why the two Rust/TS mirrors of
 * the same Python rule have to be kept in sync by hand.
 */
export type FleetChecks = MachineHealthCheckResult[]
