/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/codegen.py` from the Python dataclasses that define
 * the coordinator's wire types (coord/models.py, coord/pipeline.py) — #750.
 * Regenerate after any field change:
 *
 *     .venv/bin/python scripts/codegen.py
 *
 * `tests/test_generated_types_fixture.py` fails CI if this file drifts from
 * what the generator produces right now, so a stale checkout can't merge.
 */

export type AssignmentStatus =
  | 'pending'
  | 'running'
  | 'done'
  | 'failed'
  | 'cancelled'
  | 'advisory'
  | 'merged'

export type AssignmentType =
  | 'work'
  | 'review'
  | 'plan'
  | 'smoke'
  | 'conflict-fix'
  | 'merge'
  | 'fix'

export type TestVerdict = 'passed' | 'failed' | 'skipped'

/**
 * Actions supported by POST /api/pipeline/action.
 *
 * dispatch_review    — kick off an adversarial review assignment
 * dispatch_smoke     — kick off a smoke-test assignment
 * enqueue            — add to merge queue
 * merge              — merge a queued PR (must be in "pending" state)
 * post_findings      — post orphaned review findings to GitHub
 * unstick            — cancel a stuck assignment and mark it failed
 * retry              — (forthcoming) retry a failed work assignment
 * dispatch_fix       — (forthcoming) dispatch a fix for a test failure / review request-changes
 * test-verdict       — (forthcoming) record passed/failed/skipped test verdict
 * record-review-verdict — (forthcoming) record an approved/changes-requested review verdict
 */
export type PipelineAction =
  | 'dispatch_review'
  | 'dispatch_smoke'
  | 'enqueue'
  | 'merge'
  | 'post_findings'
  | 'unstick'
  | 'retry'
  | 'dispatch_fix'
  | 'test-verdict'
  | 'record-review-verdict'

export interface PipelineStage {
  name: string
  status: string
  is_current: boolean
}

export interface PipelineGate {
  action: PipelineAction
  label: string
  endpoint: string
}

export interface PipelineView {
  assignment_id: string
  issue_number: number
  issue_title: string
  repo_name: string
  machine_name: string
  stages: PipelineStage[]
  current_stage: string
  available_gates: PipelineGate[]
  progress_pct: number
  review_findings_pending: boolean
  review_verdict: 'approve' | 'request-changes' | null
  review_findings_body: string | null
  test_verdict: TestVerdict | null
  needs_attention: boolean
  needs_attention_reason: string | null
  needs_attention_detail: string | null
  finished_at: number | null
}

export interface Assignment {
  machine_name: string
  repo_name: string
  issue_number: number
  issue_title: string
  files_allowed: string[]
  files_forbidden: string[]
  briefing: string
  assignment_id: string | null
  status: AssignmentStatus
  branch: string | null
  pr_url: string | null
  dispatched_at: number | null
  finished_at: number | null
  smoke_test: 'pass' | 'fail' | null
  smoke_test_reason: string | null
  type: AssignmentType
  review_target: string | null
  review_of_assignment_id: string | null
  unreachable_count: number
  model: string | null
  plan: Record<string, unknown> | null
  review_state: 'pending' | 'dispatched' | 'done' | null
  required_gates: string[]
  review_iteration: number
  review_posted_at: number | null
  test_state: TestVerdict | null
  test_reason: string | null
  review_verdict: 'approve' | 'request-changes' | null
  review_head_sha: string | null
  cost_usd: number | null
  smoke_tests: string[] | null
  provider_name: string | null
  input_tokens: number
  output_tokens: number
  cache_creation_tokens: number
  cache_read_tokens: number
  failure_reason: string | null
  acceptance_state: string | null
  acceptance_reason: string | null
  acceptance_sha: string | null
  acceptance_total: number | null
  acceptance_passed: number | null
  completion_summary: string | null
  audit_goals_json: string | null
  audit_bottom_line: string | null
  audit_run_number: number | null
  for_issue_number: number | null
}
